astra_db:
  collection_name: "ecommerce_data"

embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 4

llm:
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0
    max_output_tokens: 2048

  openai:
    provider: "openai"
    model_name: "gpt-4.o"
    temperature: 0
    max_output_tokens: 2048
  
  anthropic:
    provider: "anthropic"
    model_name: "claude-2"
    temperature: 0
    max_output_tokens: 2048